
package fatec.poo.view;

import fatec.poo.model.Aluno;
import fatec.poo.model.Pessoa;
import static fatec.poo.model.Pessoa.validarCPF;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GuiAluno extends javax.swing.JFrame {

    /**
     * Creates new form GuiAluno
     */
    public GuiAluno(ArrayList<Pessoa> cadAlunoInstrutor) {
        initComponents();
        cadastro = cadAlunoInstrutor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnInserir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        cbxSexo = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cbxEstadoCivil = new javax.swing.JComboBox<>();
        txtRg = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JFormattedTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        cbxEscolaridade = new javax.swing.JComboBox<>();
        txtEndereco = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JFormattedTextField();
        txtBairro = new javax.swing.JFormattedTextField();
        jLabel15 = new javax.swing.JLabel();
        txtCep = new javax.swing.JFormattedTextField();
        txtCidade = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtCpf = new javax.swing.JFormattedTextField();
        txtCelular = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxTipo = new javax.swing.JComboBox<>();

        jLabel2.setText("jLabel2");

        jLabel4.setText("Sexo");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastrar Aluno");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setText("CPF");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Nome");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Sexo");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setText("Bairro");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setText("Endereço");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setText("Cidade");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setText("RG");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setText("Email");

        btnInserir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.setMaximumSize(new java.awt.Dimension(105, 25));
        btnInserir.setMinimumSize(new java.awt.Dimension(105, 25));
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnConsultar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setMaximumSize(new java.awt.Dimension(105, 25));
        btnConsultar.setMinimumSize(new java.awt.Dimension(105, 25));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.setMaximumSize(new java.awt.Dimension(105, 25));
        btnAlterar.setMinimumSize(new java.awt.Dimension(105, 25));
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Feminino", "Masculino" }));
        cbxSexo.setSelectedIndex(-1);
        cbxSexo.setToolTipText("");
        cbxSexo.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setText("Estado Civil");

        cbxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Solteiro (a)", "Casado (a)", "Viúvo (a)", "Divorciado (a)" }));
        cbxEstadoCivil.setSelectedIndex(-1);
        cbxEstadoCivil.setEnabled(false);

        try {
            txtRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtRg.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRg.setEnabled(false);
        txtRg.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtRg.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtNome.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNome.setEnabled(false);
        txtNome.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtNome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDataNascimento.setEnabled(false);
        txtDataNascimento.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtDataNascimento.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        cbxEscolaridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ensino Fundamental", "Ensino Médio", "Ensino Superior", "Pós Graduação", "Mestrado", "Doutorado" }));
        cbxEscolaridade.setSelectedIndex(-1);
        cbxEscolaridade.setEnabled(false);

        txtEndereco.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtEndereco.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEndereco.setEnabled(false);
        txtEndereco.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtEndereco.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setText("Nº");

        txtNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        txtNumero.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNumero.setEnabled(false);
        txtNumero.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtNumero.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtBairro.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtBairro.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtBairro.setEnabled(false);
        txtBairro.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtBairro.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setText("CEP");

        try {
            txtCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCep.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCep.setEnabled(false);
        txtCep.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCep.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtCidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtCidade.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCidade.setEnabled(false);
        txtCidade.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCidade.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setText("Estado");

        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbxEstado.setSelectedIndex(-1);
        cbxEstado.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setText("Tel. Res");

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefone.setEnabled(false);
        txtTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setText("Data Nascimento");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setText("Escolaridade");

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCelular.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCelular.setEnabled(false);
        txtCelular.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCelular.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setText("Celular");

        txtEmail.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtEmail.setEnabled(false);
        txtEmail.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        jLabel12.setText("Tipo");

        cbxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comum", "Especial" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtNome)
                            .addComponent(txtEndereco)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxEscolaridade, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCep, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRg, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCelular, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbxTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxSexo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxEstadoCivil, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbxEscolaridade, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEndereco, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNumero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBairro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCep, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCidade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtRg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExcluir)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        // Validando CPF       
        String cpf = txtCpf.getText().replaceAll("[\\.\\-]", "");
        
        if (!validarCPF(cpf)) {
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(
                    frame,
                    "Insira um CPF válido",
                    "Mensagem de Erro",
                    JOptionPane.ERROR_MESSAGE
            );
            txtCpf.requestFocus();
            return;
        }
        
        int i;
        posAluno = -1; // padrao aluno nao encontrado

        for (i = 0; i < cadastro.size(); i++) {
            if (cadastro.get(i).getCpf().equals(cpf)) {
                posAluno = i; // define aluno encontrado
            }
        }
        
        // Desabilitando cpf e habilitando demais campos
        txtCpf.setEnabled(false);
        txtNome.setEnabled(true);
        txtDataNascimento.setEnabled(true);
        cbxTipo.setEnabled(true);
        cbxSexo.setEnabled(true);
        cbxEstadoCivil.setEnabled(true);
        cbxEscolaridade.setEnabled(true);
        txtEndereco.setEnabled(true);
        txtNumero.setEnabled(true);           
        txtBairro.setEnabled(true);
        txtCep.setEnabled(true);
        txtCidade.setEnabled(true);
        cbxEstado.setEnabled(true);
        txtTelefone.setEnabled(true);
        txtRg.setEnabled(true);
        txtCelular.setEnabled(true);
        txtEmail.setEnabled(true);
        
        // Desabilitando consultar e foco no nome  
        btnConsultar.setEnabled(false);    
        txtNome.requestFocus();
        
        if (posAluno > -1) {
            Aluno aluno = (Aluno) cadastro.get(posAluno);
            txtNome.setText(aluno.getNome());
            txtDataNascimento.setText(aluno.getDataNasc());
            cbxTipo.setSelectedItem(aluno.getTipo());
            cbxSexo.setSelectedItem(aluno.getSexo());
            cbxEstadoCivil.setSelectedItem(aluno.getEstadoCivil());
            cbxEscolaridade.setSelectedItem(aluno.getEscolaridade());
            txtEndereco.setText(aluno.getEndereco());
            txtNumero.setText(Integer.toString(aluno.getNumero()));            
            txtBairro.setText(aluno.getBairro());
            txtCep.setText(aluno.getCep());
            txtCidade.setText(aluno.getCidade());
            cbxEstado.setSelectedItem(aluno.getEstado());
            txtTelefone.setText(aluno.getTelefone());
            txtRg.setText(aluno.getRg());
            txtCelular.setText(aluno.getCelular());
            txtEmail.setText(aluno.getEmail());
            
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);   
            
            return;
        }
        
        btnInserir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        // Instanciando o objeto aluno
        Aluno aluno = new Aluno(txtCpf.getText().replaceAll("[\\.\\-]", ""), txtNome.getText());
        aluno.setDataNasc(txtDataNascimento.getText().replaceAll("[\\/]", ""));
        aluno.setTipo(cbxTipo.getSelectedItem().toString());
        aluno.setSexo(cbxSexo.getSelectedItem().toString());
        aluno.setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());
        aluno.setEscolaridade(cbxEscolaridade.getSelectedItem().toString());
        aluno.setEndereco(txtEndereco.getText());
        aluno.setNumero(Integer.valueOf(txtNumero.getText()));
        aluno.setBairro(txtBairro.getText());
        aluno.setCep(txtCep.getText().replaceAll("[\\-]", ""));
        aluno.setCidade(txtCidade.getText());
        aluno.setEstado(cbxEstado.getSelectedItem().toString());
        aluno.setTelefone(txtTelefone.getText().replaceAll("[\\(\\)\\-\\s]", ""));
        aluno.setRg(txtRg.getText().replaceAll("[\\.\\-]", ""));
        aluno.setCelular(txtCelular.getText().replaceAll("[\\(\\)\\-\\s]", ""));
        aluno.setEmail(txtEmail.getText());
        
        // Salvando no arraylist
        cadastro.add(aluno);
        
        // Limpando campos
        txtCpf.setText(null);
        txtNome.setText(null);
        txtDataNascimento.setText(null);
        cbxTipo.setSelectedIndex(-1);
        cbxSexo.setSelectedIndex(-1);
        cbxEstadoCivil.setSelectedIndex(-1);
        cbxEscolaridade.setSelectedIndex(-1);
        txtEndereco.setText(null);
        txtNumero.setText(null);            
        txtBairro.setText(null);
        txtCep.setText(null);
        txtCidade.setText(null);
        cbxEstado.setSelectedIndex(-1);
        txtTelefone.setText(null);
        txtRg.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        
        //Habilitando consulta e desabilitando os demais        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Habilitando cpf e desabilitando demais campos
        txtCpf.setEnabled(true);
        txtNome.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        cbxTipo.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);           
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtRg.setEnabled(false);
        txtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        
        // Foco no cpf
        txtCpf.requestFocus();
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // Alterando o objeto aluno
        cadastro.get(posAluno).setNome(txtNome.getText()); 
        cadastro.get(posAluno).setDataNasc(txtDataNascimento.getText().replaceAll("[\\/]", ""));
        cadastro.get(posAluno).setSexo(cbxTipo.getSelectedItem().toString());
        cadastro.get(posAluno).setSexo(cbxSexo.getSelectedItem().toString());
        cadastro.get(posAluno).setEstadoCivil(cbxEstadoCivil.getSelectedItem().toString());
        ((Aluno) cadastro.get(posAluno)).setEscolaridade(cbxEscolaridade.getSelectedItem().toString());
        cadastro.get(posAluno).setEndereco(txtEndereco.getText());
        cadastro.get(posAluno).setNumero(Integer.valueOf(txtNumero.getText()));
        cadastro.get(posAluno).setBairro(txtBairro.getText());
        cadastro.get(posAluno).setCep(txtCep.getText().replaceAll("[\\-]", ""));
        cadastro.get(posAluno).setCidade(txtCidade.getText());
        cadastro.get(posAluno).setEstado(cbxEstado.getSelectedItem().toString());
        cadastro.get(posAluno).setTelefone(txtTelefone.getText().replaceAll("[\\(\\)\\-\\s]", ""));
        cadastro.get(posAluno).setRg(txtRg.getText().replaceAll("[\\.\\-]", ""));
        cadastro.get(posAluno).setCelular(txtCelular.getText().replaceAll("[\\(\\)\\-\\s]", ""));
        cadastro.get(posAluno).setEmail(txtEmail.getText());
        
        // Limpando campos
        txtCpf.setText(null);
        txtNome.setText(null);
        txtDataNascimento.setText(null);
        cbxTipo.setSelectedIndex(-1);
        cbxSexo.setSelectedIndex(-1);
        cbxEstadoCivil.setSelectedIndex(-1);
        cbxEscolaridade.setSelectedIndex(-1);
        txtEndereco.setText(null);
        txtNumero.setText(null);            
        txtBairro.setText(null);
        txtCep.setText(null);
        txtCidade.setText(null);
        cbxEstado.setSelectedIndex(-1);
        txtTelefone.setText(null);
        txtRg.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        
        //Habilitando consulta e desabilitando os demais        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Habilitando cpf e desabilitando demais campos
        txtCpf.setEnabled(true);
        txtNome.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        cbxTipo.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);           
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtRg.setEnabled(false);
        txtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        
        // Foco no cpf
        txtCpf.requestFocus();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (posAluno >= 0) {
            cadastro.remove(posAluno);
            posAluno = -1;
        }
        
        // Limpando campos
        txtCpf.setText(null);
        txtNome.setText(null);
        txtDataNascimento.setText(null);
        cbxTipo.setSelectedIndex(-1);
        cbxSexo.setSelectedIndex(-1);
        cbxEstadoCivil.setSelectedIndex(-1);
        cbxEscolaridade.setSelectedIndex(-1);
        txtEndereco.setText(null);
        txtNumero.setText(null);            
        txtBairro.setText(null);
        txtCep.setText(null);
        txtCidade.setText(null);
        cbxEstado.setSelectedIndex(-1);
        txtTelefone.setText(null);
        txtRg.setText(null);
        txtCelular.setText(null);
        txtEmail.setText(null);
        
        //Habilitando consulta e desabilitando os demais        
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Habilitando cpf e desabilitando demais campos
        txtCpf.setEnabled(true);
        txtNome.setEnabled(false);
        txtDataNascimento.setEnabled(false);
        cbxTipo.setEnabled(false);
        cbxSexo.setEnabled(false);
        cbxEstadoCivil.setEnabled(false);
        cbxEscolaridade.setEnabled(false);
        txtEndereco.setEnabled(false);
        txtNumero.setEnabled(false);           
        txtBairro.setEnabled(false);
        txtCep.setEnabled(false);
        txtCidade.setEnabled(false);
        cbxEstado.setEnabled(false);
        txtTelefone.setEnabled(false);
        txtRg.setEnabled(false);
        txtCelular.setEnabled(false);
        txtEmail.setEnabled(false);
        
        // Foco no cpf
        txtCpf.requestFocus();
    }//GEN-LAST:event_btnExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxEscolaridade;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxEstadoCivil;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JFormattedTextField txtBairro;
    private javax.swing.JFormattedTextField txtCelular;
    private javax.swing.JFormattedTextField txtCep;
    private javax.swing.JFormattedTextField txtCidade;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JFormattedTextField txtEmail;
    private javax.swing.JFormattedTextField txtEndereco;
    private javax.swing.JFormattedTextField txtNome;
    private javax.swing.JFormattedTextField txtNumero;
    private javax.swing.JFormattedTextField txtRg;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadastro;
    private int posAluno;
}
