/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Curso;
import fatec.poo.model.Instrutor;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Turma;
import java.util.ArrayList;

public class GuiAlocarInstrutor extends javax.swing.JFrame {

    /**
     * Creates new form GuiAlocarInstrutor
     */
    public GuiAlocarInstrutor(ArrayList<Curso> cadCurso,
                              ArrayList<Turma> cadTurma,
                              ArrayList<Pessoa> cadAlunoInstrutor) {
        initComponents();
        this.cadAlunoInstrutor = cadAlunoInstrutor;
        this.cadastroC = cadCurso;
        this.cadastroT = cadTurma;
        this.cadastroI = new ArrayList<>();
                
        //Preenchendo o cbxCurso ao carregar a Gui
        ArrayList<String> relCursos;
        relCursos = Curso.listarSiglas(cadastroC);
        for (int x = 0; x < relCursos.size(); x++){
            cbxCurso.addItem(relCursos.get(x));            
        }
                
        // Add no cadastroI apenas a Pessoa que é Instrutor    
        for (Pessoa pessoa : cadAlunoInstrutor) {
            if (pessoa instanceof Instrutor) {
                cadastroI.add((Instrutor) pessoa);
            }
        }
 
        ArrayList<String> relInstrutor;
        relInstrutor = Instrutor.listarInstrutor(cadastroI);
        for (int x = 0; x < relInstrutor.size(); x++){
            cbxInstrutor.addItem(relInstrutor.get(x));            
        }
        cbxCurso.setSelectedIndex(-1);               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSituacao = new javax.swing.JTextField();
        cbxCurso = new javax.swing.JComboBox<>();
        cbxTurma = new javax.swing.JComboBox<>();
        cbxInstrutor = new javax.swing.JComboBox<>();
        btnAlocar = new javax.swing.JButton();
        btnLiberar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Alocar Instrutor");

        jLabel1.setText("Curso");

        jLabel2.setText("Turma");

        jLabel3.setText("Instrutor");

        jLabel4.setText("Situação");

        txtSituacao.setEnabled(false);

        cbxCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxCursoActionPerformed(evt);
            }
        });

        cbxTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxTurmaActionPerformed(evt);
            }
        });

        btnAlocar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnAlocar.setText("Alocar");
        btnAlocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlocarActionPerformed(evt);
            }
        });

        btnLiberar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnLiberar.setText("Liberar");
        btnLiberar.setEnabled(false);
        btnLiberar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiberarActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(37, 37, 37))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3)))
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cbxTurma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbxCurso, javax.swing.GroupLayout.Alignment.LEADING, 0, 128, Short.MAX_VALUE))
                            .addComponent(cbxInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(btnAlocar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLiberar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAlocar, btnLiberar, btnSair});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbxTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(cbxInstrutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(txtSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAlocar)
                    .addComponent(btnLiberar)
                    .addComponent(btnSair))
                .addGap(22, 22, 22))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnAlocar, btnLiberar, btnSair});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAlocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlocarActionPerformed
        //Estabelecendo a associação binária entre um objeto Turma
        //com um objeto Instrutor
        
        Turma turma = null;
        
        for (int i = 0; i < cadastroT.size(); i++) {
            if (cadastroT.get(i).getSiglaTurma().equals((String) cbxTurma.getSelectedItem())) {
                turma = cadastroT.get(i);
            }
        }
        
        cadastroI.get(cbxInstrutor.getSelectedIndex()).addTurma(turma);
                  
        txtSituacao.setText("Alocada");
        
        btnAlocar.setEnabled(false);
        btnLiberar.setEnabled(true);
        btnSair.setEnabled(true);
    }//GEN-LAST:event_btnAlocarActionPerformed

    private void btnLiberarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiberarActionPerformed
        //remove a associação binaria entre Instrutor e Turma
        Turma turma = null;
        
        for (int i = 0; i < cadastroT.size(); i++) {
            if (cadastroT.get(i).getSiglaTurma().equals((String) cbxTurma.getSelectedItem())) {
                turma = cadastroT.get(i);
            }
        }

        cadastroI.get(cbxInstrutor.getSelectedIndex()).removeTurma(turma);   
        
        txtSituacao.setText("Liberada");
        
        btnAlocar.setEnabled(true);
        btnLiberar.setEnabled(false);
        btnSair.setEnabled(true);
    }//GEN-LAST:event_btnLiberarActionPerformed

    private void cbxCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxCursoActionPerformed
        int x;

        ArrayList<String> relTurmas;
        relTurmas = Turma.listarTurma(cadastroT);
        cbxTurma.removeAllItems();
        
        for (x = 0; x < relTurmas.size(); x++){
            if(cadastroT.get(x).getCurso().getSigla().equals(cbxCurso.getSelectedItem())){
                cbxTurma.addItem(relTurmas.get(x));                
            }            
        }
        
        cbxTurma.setSelectedIndex(-1);
        cbxInstrutor.setSelectedIndex(-1); 
        txtSituacao.setText(" ");        
    }//GEN-LAST:event_cbxCursoActionPerformed

    private void cbxTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxTurmaActionPerformed
        ArrayList<String> relTurmas;
        relTurmas = Turma.listarTurma(cadastroT);
        
        for (int x = 0; x < relTurmas.size(); x++){
            if(cadastroT.get(x).getSiglaTurma().equals(cbxTurma.getSelectedItem())){
                if(cadastroT.get(x).getInstrutor() == null){                    
                    txtSituacao.setText(" ");
                    cbxInstrutor.setSelectedIndex(-1);
                    btnAlocar.setEnabled(true);
                    btnLiberar.setEnabled(false);
                    btnSair.setEnabled(true);                    
                }else{
                    //Atualizando o cbxInstrutor de acordo
                    //como a turma associada
                    cbxInstrutor.setSelectedItem(cadastroT.get(x).getInstrutor().getNome());
                    txtSituacao.setText("Alocada");
                    btnAlocar.setEnabled(false);
                    btnLiberar.setEnabled(true);
                    btnSair.setEnabled(true);
                }                    
            }
        }
    }//GEN-LAST:event_cbxTurmaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlocar;
    private javax.swing.JButton btnLiberar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cbxCurso;
    private javax.swing.JComboBox<String> cbxInstrutor;
    private javax.swing.JComboBox<String> cbxTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtSituacao;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadAlunoInstrutor;
    private ArrayList<Curso> cadastroC;
    private ArrayList<Turma> cadastroT;
    private ArrayList<Instrutor> cadastroI;
    private int posInstrutor;
}
