/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Aluno;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Pessoa;
import static fatec.poo.model.Pessoa.validarCPF;
import fatec.poo.model.Turma;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class GuiEfetuarMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiMatricula
     */
    public GuiEfetuarMatricula(
                                ArrayList<Pessoa> cadAlunoInstrutor,
                                ArrayList<Curso> cadCurso,
                                ArrayList<Turma> cadTurma,
                                ArrayList<Matricula> cadMatricula,
                                ArrayList<AVista> cadAVista,
                                ArrayList<APrazo> cadAPrazo) {
        initComponents();
        this.cadAlunoInstrutor = cadAlunoInstrutor;
        this.cadCurso = cadCurso;
        this.cadTurma = cadTurma;
        this.cadMatricula = cadMatricula;
        this.cadAPrazo = cadAPrazo;
        this.cadAVista = cadAVista;
        
        ArrayList<String> relCursos;
        relCursos = Curso.listarSiglas(cadCurso);
        for (int x = 0; x < relCursos.size(); x++){
            cboCurso.addItem(relCursos.get(x));
        }
        
        cboCurso.setSelectedIndex(-1);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnConsultar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtDataMatricula = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rdbAVista = new javax.swing.JRadioButton();
        rdbParcelado = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtAgencia = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCheque = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtMensalidades = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        txtJuros = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        txtDataPagto = new javax.swing.JFormattedTextField();
        txtDataVencto = new javax.swing.JFormattedTextField();
        cboCurso = new javax.swing.JComboBox<>();
        cboTurma = new javax.swing.JComboBox<>();
        txtCpf = new javax.swing.JFormattedTextField();
        txtValor = new javax.swing.JFormattedTextField();
        txtNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Efetuar Matrícula");

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Consultar.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Inserir.png"))); // NOI18N
        btnInserir.setText("Inserir");
        btnInserir.setEnabled(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Alterar.png"))); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.setEnabled(false);
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Remover.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fatec/poo/view/icon/Sair.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel1.setText("Data da Matrícula");

        try {
            txtDataMatricula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Curso");

        jLabel3.setText("Turma");

        jLabel4.setText("CPF Aluno");

        jLabel5.setText("Valor");

        jLabel6.setText("Nome");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pagamento"));

        buttonGroup1.add(rdbAVista);
        rdbAVista.setSelected(true);
        rdbAVista.setText("À Vista");
        rdbAVista.setEnabled(false);
        rdbAVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbAVistaActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdbParcelado);
        rdbParcelado.setText("Parcelado");
        rdbParcelado.setEnabled(false);
        rdbParcelado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbParceladoActionPerformed(evt);
            }
        });

        jLabel7.setText("Agência");

        txtAgencia.setEnabled(false);

        jLabel8.setText("Nº Cheque");

        txtCheque.setEnabled(false);

        jLabel9.setText("Data Pagto.");

        jLabel10.setText("Qtde. Mensalidades");

        txtMensalidades.setEnabled(false);

        jLabel11.setText("Tx. Juros (%) ");

        txtJuros.setEnabled(false);

        jLabel12.setText("Data 1o Vencto.");

        try {
            txtDataPagto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataPagto.setEnabled(false);

        try {
            txtDataVencto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVencto.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbParcelado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addGap(3, 3, 3)
                        .addComponent(txtMensalidades, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rdbAVista)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtJuros)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataVencto, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbAVista)
                    .addComponent(jLabel7)
                    .addComponent(txtAgencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataPagto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdbParcelado)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(txtMensalidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVencto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        cboCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboCursoActionPerformed(evt);
            }
        });

        cboTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTurmaActionPerformed(evt);
            }
        });

        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtCpf.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtCpf.setEnabled(false);
        txtCpf.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        txtCpf.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        txtValor.setEnabled(false);

        txtNome.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtDataMatricula))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(139, 139, 139)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtCpf)
                                            .addComponent(cboCurso, javax.swing.GroupLayout.Alignment.TRAILING, 0, 130, Short.MAX_VALUE)
                                            .addComponent(cboTurma, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addComponent(jLabel2))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInserir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSair)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDataMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(cboCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(cboTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(btnInserir)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair)
                    .addComponent(btnAlterar))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        
        // Turma selecionada
        Turma turma = cadTurma.get(cboTurma.getSelectedIndex());
        
        // Obtendo objeto Aluno
        Aluno aluno = null;
        
        for (Pessoa pessoa : cadAlunoInstrutor) {
            if (
                pessoa instanceof Aluno &&
                ((Aluno) pessoa).getCpf().equals(txtCpf.getText().replaceAll("[\\.\\-]", ""))
            ) {
                aluno = (Aluno) pessoa;
            }
        }
        
        // Instanciando Matricula
        Matricula matricula = new Matricula(txtDataMatricula.getText().replaceAll("/", ""));
        matricula.setAluno(aluno);
        matricula.setTurma(turma);
        
        if (rdbAVista.isSelected()) {                     
            AVista aVista = new AVista();
            aVista.setValor(Double.valueOf(txtValor.getText()));
            aVista.setAgencia(Integer.valueOf(txtAgencia.getText()));
            aVista.setNCheque(Integer.valueOf(txtCheque.getText()));
            aVista.setPreData(txtDataPagto.getText().replaceAll("/", ""));
            
            matricula.setAVista(aVista);
            
            cadAVista.add(aVista);
        }
        else {
            APrazo aPrazo = new APrazo();
            aPrazo.setValor(Double.valueOf(txtValor.getText()));
            aPrazo.setDtVencimento(txtDataVencto.getText().replaceAll("/", ""));
            aPrazo.setTaxaJuros(Double.valueOf(txtJuros.getText()));
            aPrazo.setQtdeMensalidade(Integer.valueOf(txtMensalidades.getText()));
            
            matricula.setAPrazo(aPrazo);
            
            cadAPrazo.add(aPrazo);
        }
        
        // salvando matricula na lista
        cadMatricula.add(matricula);
        
        // Limpando campos
        txtDataMatricula.setText(null);
        cboCurso.setSelectedIndex(-1);
        txtValor.setText(null);
        cboTurma.setSelectedIndex(-1);
        txtCpf.setText(null);
        txtNome.setText(null);
        
        rdbAVista.setSelected(true);
        rdbParcelado.setSelected(false);
        txtAgencia.setText(null);
        txtCheque.setText(null);
        txtDataPagto.setText(null);
        
        txtMensalidades.setText(null);
        txtJuros.setText(null);
        txtDataVencto.setText(null);  
        
        // Habilitando botoes
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Habilitando campos
        txtDataMatricula.setEnabled(true);
        txtCpf.setEnabled(true);
        
        jPanel1.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtCheque.setEnabled(false);
        txtDataPagto.setEnabled(false);
        
        txtMensalidades.setEnabled(false);
        txtJuros.setEnabled(false);
        txtDataVencto.setEnabled(false);
    }//GEN-LAST:event_btnInserirActionPerformed

    private void rdbAVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbAVistaActionPerformed
        rdbAVista.setSelected(true);
        rdbAVista.setEnabled(false);
        
        rdbParcelado.setSelected(false);
        rdbParcelado.setEnabled(true);
        
        txtAgencia.setEnabled(true);
        txtCheque.setEnabled(true);
        txtDataPagto.setEnabled(true);
        
        txtMensalidades.setEnabled(false);
        txtJuros.setEnabled(false);
        txtDataVencto.setEnabled(false);
    }//GEN-LAST:event_rdbAVistaActionPerformed

    private void rdbParceladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbParceladoActionPerformed
        rdbAVista.setSelected(false);
        rdbAVista.setEnabled(true);
        
        rdbParcelado.setSelected(true);
        rdbParcelado.setEnabled(false);
        
        txtAgencia.setEnabled(false);
        txtCheque.setEnabled(false);
        txtDataPagto.setEnabled(false);
        
        txtMensalidades.setEnabled(true);
        txtJuros.setEnabled(true);
        txtDataVencto.setEnabled(true);
    }//GEN-LAST:event_rdbParceladoActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        
        if (rdbAVista.isSelected()) {   
            // Se anteriormente o pagamento fosse a prazo
            if (cadMatricula.get(posMatricula).getAVista() == null) {
                
                // Removendo objeto APrazo antigo
                APrazo aPrazo = cadMatricula.get(posMatricula).getAPrazo();          
                cadAPrazo.remove(aPrazo);           
                cadMatricula.get(posMatricula).setAPrazo(null);
                
                // Instanciando AVista
                AVista aVista = new AVista();
                aVista.setValor(Double.valueOf(txtValor.getText()));
                aVista.setAgencia(Integer.valueOf(txtAgencia.getText()));
                aVista.setNCheque(Integer.valueOf(txtCheque.getText()));
                aVista.setPreData(txtDataPagto.getText().replaceAll("/", ""));

                cadMatricula.get(posMatricula).setAVista(aVista);
                cadAVista.add(aVista);      
            }
            else {
                // Remove objeto AVista antigo da lista
                cadAVista.remove(cadMatricula.get(posMatricula).getAVista());
                
                // Alterando objeto AVista
                cadMatricula.get(posMatricula).getAVista().setValor(Double.valueOf(txtValor.getText()));
                cadMatricula.get(posMatricula).getAVista().setAgencia(Integer.valueOf(txtAgencia.getText()));
                cadMatricula.get(posMatricula).getAVista().setNCheque(Integer.valueOf(txtCheque.getText()));
                cadMatricula.get(posMatricula).getAVista().setPreData(txtDataPagto.getText().replaceAll("/", ""));
                
                // Add objeto AVista modificado na lista
                cadAVista.add(cadMatricula.get(posMatricula).getAVista());      
            }
        }
        else {
            if (cadMatricula.get(posMatricula).getAPrazo() == null) { 
                // Removendo objeto AVista antigo
                AVista aVista = cadMatricula.get(posMatricula).getAVista();          
                cadAVista.remove(aVista);           
                cadMatricula.get(posMatricula).setAVista(null);
                
                // Instanciando AVista
                APrazo aPrazo = new APrazo();
                aPrazo.setValor(Double.valueOf(txtValor.getText()));
                aPrazo.setDtVencimento(txtDataVencto.getText().replaceAll("/", ""));
                aPrazo.setTaxaJuros(Double.valueOf(txtJuros.getText()));
                aPrazo.setQtdeMensalidade(Integer.valueOf(txtMensalidades.getText()));

                cadMatricula.get(posMatricula).setAPrazo(aPrazo);
                cadAPrazo.add(aPrazo);      
            }
            else {    
                // Remove objeto APrazo antigo da lista
                cadAPrazo.remove(cadMatricula.get(posMatricula).getAPrazo());
                
                // Alterando objeto APrazo
                cadMatricula.get(posMatricula).getAPrazo().setValor(Double.valueOf(txtValor.getText()));
                cadMatricula.get(posMatricula).getAPrazo().setDtVencimento(txtDataVencto.getText().replaceAll("/", ""));
                cadMatricula.get(posMatricula).getAPrazo().setTaxaJuros(Double.valueOf(txtJuros.getText()));
                cadMatricula.get(posMatricula).getAPrazo().setQtdeMensalidade(Integer.valueOf(txtMensalidades.getText()));
                
                // Add objeto APrazo modificado na lista
                cadAPrazo.add(cadMatricula.get(posMatricula).getAPrazo()); 
            }
            
        }
        
        // Limpando campos
        txtDataMatricula.setText(null);
        cboCurso.setSelectedIndex(-1);
        txtValor.setText(null);
        cboTurma.setSelectedIndex(-1);
        txtCpf.setText(null);
        txtNome.setText(null);
        
        rdbAVista.setSelected(true);
        rdbParcelado.setSelected(false);
        
        txtAgencia.setText(null);
        txtCheque.setText(null);
        txtDataPagto.setText(null);
        
        txtMensalidades.setText(null);
        txtJuros.setText(null);
        txtDataVencto.setText(null);  
        
        // Habilitando botoes
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Habilitando campos
        txtDataMatricula.setEnabled(true);
        txtCpf.setEnabled(true);
        
        jPanel1.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtCheque.setEnabled(false);
        txtDataPagto.setEnabled(false);
        
        txtMensalidades.setEnabled(false);
        txtJuros.setEnabled(false);
        txtDataVencto.setEnabled(false);
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (posMatricula >= 0) {
            
            if (cadMatricula.get(posMatricula).getAPrazo() != null) {
                APrazo aPrazo = cadMatricula.get(posMatricula).getAPrazo();
                cadAPrazo.remove(aPrazo);
            }
            else {
                AVista aVista = cadMatricula.get(posMatricula).getAVista();
                cadAPrazo.remove(aVista);
            }      
            
            cadMatricula.get(posMatricula).setAluno(null);
            cadMatricula.remove(posMatricula);
            posMatricula = -1;
        }
        
        // Limpando campos
        txtDataMatricula.setText(null);
        cboCurso.setSelectedIndex(-1);
        txtValor.setText(null);
        cboTurma.setSelectedIndex(-1);
        txtCpf.setText(null);
        txtNome.setText(null);
        
        rdbAVista.setSelected(true);
        rdbParcelado.setSelected(false);
        
        txtAgencia.setText(null);
        txtCheque.setText(null);
        txtDataPagto.setText(null);
        
        txtMensalidades.setText(null);
        txtJuros.setText(null);
        txtDataVencto.setText(null);  
        
        // Habilitando botoes
        btnConsultar.setEnabled(true);
        btnInserir.setEnabled(false);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
        // Habilitando campos
        txtDataMatricula.setEnabled(true);
        txtCpf.setEnabled(true);
        
        jPanel1.setEnabled(false);
        txtAgencia.setEnabled(false);
        txtCheque.setEnabled(false);
        txtDataPagto.setEnabled(false);
        
        txtMensalidades.setEnabled(false);
        txtJuros.setEnabled(false);
        txtDataVencto.setEnabled(false);
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        
        // Validando CPF
        String cpf = txtCpf.getText().replaceAll("[\\.\\-]", "");
        
        if (!validarCPF(cpf)) {
            JOptionPane.showMessageDialog(null,"Informe um CPF válido", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtCpf.requestFocus();
            return;
        }
        
        Aluno aluno = null;
        
        for (Pessoa pessoa : cadAlunoInstrutor) {
            if (
                    (pessoa instanceof Aluno) &&
                    (pessoa.getCpf().equals(cpf))
                ) {
                aluno = (Aluno) pessoa;
            }
        }
        
        // Cpf indicado não é de aluno
        if (aluno == null) {
            JOptionPane.showMessageDialog(null,"Informe um CPF de um aluno cadastrado", "Aviso", JOptionPane.ERROR_MESSAGE);
            txtCpf.requestFocus();
            return;
        }
                  
        int i;
        posMatricula = -1;  // padrao Matricula nao encontrada
        
        for (i = 0; i < cadMatricula.size(); i++) {
            if (cadMatricula.get(i).getAluno().getCpf().equals(cpf)) {
                posMatricula = i; 
            }
        }
        
        txtCpf.setEnabled(false); 
        jPanel1.setEnabled(true);
        txtNome.setText(aluno.getNome());
        btnConsultar.setEnabled(false);
        
        if (posMatricula > -1) {
            if (cadMatricula.get(posMatricula).getAVista() != null) {
                AVista aVista = cadMatricula.get(posMatricula).getAVista();
                txtAgencia.setText(String.valueOf(aVista.getAgencia()));
                txtCheque.setText(String.valueOf(aVista.getNCheque()));
                txtDataPagto.setText(aVista.getPreData());
                
                txtMensalidades.setText(null);
                txtJuros.setText(null);
                txtDataVencto.setText(null);
  
                rdbAVista.setSelected(true);
                txtAgencia.setEnabled(true);
                txtCheque.setEnabled(true);
                txtDataPagto.setEnabled(true);

                rdbParcelado.setSelected(false);
                txtMensalidades.setEnabled(false);
                txtJuros.setEnabled(false);
                txtDataVencto.setEnabled(false);
            }
            else {
                APrazo aPrazo = cadMatricula.get(posMatricula).getAPrazo();
                txtMensalidades.setText(String.valueOf(aPrazo.getQtdeMensalidade()));
                txtJuros.setText(String.valueOf(aPrazo.getTaxaJuros()));
                txtDataVencto.setText(aPrazo.getDtVencimento());
                
                txtAgencia.setText(null);
                txtCheque.setText(null);
                txtDataPagto.setText(null);
                
                rdbAVista.setSelected(false);
                txtAgencia.setEnabled(false);
                txtCheque.setEnabled(false);
                txtDataPagto.setEnabled(false);

                rdbParcelado.setSelected(true);
                txtMensalidades.setEnabled(true);
                txtJuros.setEnabled(true);
                txtDataVencto.setEnabled(true);
            } 
            
            btnInserir.setEnabled(false);
            btnAlterar.setEnabled(true);
            btnExcluir.setEnabled(true);    
            
            return;
        }
        
        txtAgencia.setText(null);
        txtCheque.setText(null);
        txtDataPagto.setText(null);
        
        txtMensalidades.setText(null);
        txtJuros.setText(null);
        txtDataVencto.setText(null);

        rdbAVista.setSelected(true);
        txtAgencia.setEnabled(true);
        txtCheque.setEnabled(true);
        txtDataPagto.setEnabled(true);

        rdbParcelado.setSelected(false);
        rdbParcelado.setEnabled(true);
        txtMensalidades.setEnabled(false);
        txtJuros.setEnabled(false);
        txtDataVencto.setEnabled(false);
        
        btnInserir.setEnabled(true);
        btnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);    
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void cboCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboCursoActionPerformed
        int x;
        ArrayList<String> relTurmas;
        relTurmas = Turma.listarTurma(cadTurma);
        cboTurma.removeAllItems();
        
        for (x = 0; x < relTurmas.size(); x++){
            if(cadTurma.get(x).getCurso().getSigla().equals(cboCurso.getSelectedItem())){
                cboTurma.addItem(relTurmas.get(x));
                txtValor.setText(Double.toString(cadTurma.get(x).getCurso().getValor()));
            }            
        }
        cboTurma.setSelectedIndex(-1);
    }//GEN-LAST:event_cboCursoActionPerformed

    private void cboTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTurmaActionPerformed
        txtCpf.setEnabled(true);
    }//GEN-LAST:event_cboTurmaActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboCurso;
    private javax.swing.JComboBox<String> cboTurma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rdbAVista;
    private javax.swing.JRadioButton rdbParcelado;
    private javax.swing.JFormattedTextField txtAgencia;
    private javax.swing.JFormattedTextField txtCheque;
    private javax.swing.JFormattedTextField txtCpf;
    private javax.swing.JFormattedTextField txtDataMatricula;
    private javax.swing.JFormattedTextField txtDataPagto;
    private javax.swing.JFormattedTextField txtDataVencto;
    private javax.swing.JFormattedTextField txtJuros;
    private javax.swing.JFormattedTextField txtMensalidades;
    private javax.swing.JTextField txtNome;
    private javax.swing.JFormattedTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pessoa> cadAlunoInstrutor;
    private ArrayList<Curso> cadCurso;
    private ArrayList<Turma> cadTurma;
    private ArrayList<Matricula> cadMatricula;
    private ArrayList<AVista> cadAVista;
    private ArrayList<APrazo> cadAPrazo;
    private int posMatricula;
    private int posAluno;
}
