
package fatec.poo.view;

import fatec.poo.model.APrazo;
import fatec.poo.model.AVista;
import fatec.poo.model.Curso;
import fatec.poo.model.Matricula;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Turma;
import java.util.ArrayList;

public class GuiMenu extends javax.swing.JFrame {

    /**
     * Creates new form GuiMenu
     */
    public GuiMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        jMenuBarTrabalhoPoo = new javax.swing.JMenuBar();
        jMenuCadastros = new javax.swing.JMenu();
        jMenuItemCurso = new javax.swing.JMenuItem();
        jMenuItemTurma = new javax.swing.JMenuItem();
        jMenuItemInstrutor = new javax.swing.JMenuItem();
        jMenuItemAluno = new javax.swing.JMenuItem();
        jSeparatorCadastros = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jMenuOperacoes = new javax.swing.JMenu();
        jMenuItemAlocarInstrutor = new javax.swing.JMenuItem();
        jMenuItemEfetuarMatricula = new javax.swing.JMenuItem();
        jMenuItem2aAvaliacaoPOO = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Trabalho POO");

        jMenuCadastros.setText("Cadastros");

        jMenuItemCurso.setText("Curso");
        jMenuItemCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCursoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemCurso);

        jMenuItemTurma.setText("Turma");
        jMenuItemTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTurmaActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemTurma);

        jMenuItemInstrutor.setText("Instrutor");
        jMenuItemInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInstrutorActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemInstrutor);

        jMenuItemAluno.setText("Aluno");
        jMenuItemAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlunoActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemAluno);
        jMenuCadastros.add(jSeparatorCadastros);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuCadastros.add(jMenuItemSair);

        jMenuBarTrabalhoPoo.add(jMenuCadastros);

        jMenuOperacoes.setText("Operações");

        jMenuItemAlocarInstrutor.setText("Alocar Instrutor");
        jMenuItemAlocarInstrutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlocarInstrutorActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemAlocarInstrutor);

        jMenuItemEfetuarMatricula.setText("Efetuar Matrícula");
        jMenuItemEfetuarMatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEfetuarMatriculaActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItemEfetuarMatricula);

        jMenuItem2aAvaliacaoPOO.setText("2a. Avaliação POO");
        jMenuItem2aAvaliacaoPOO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2aAvaliacaoPOOActionPerformed(evt);
            }
        });
        jMenuOperacoes.add(jMenuItem2aAvaliacaoPOO);

        jMenuBarTrabalhoPoo.add(jMenuOperacoes);

        setJMenuBar(jMenuBarTrabalhoPoo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCursoActionPerformed
        new GuiCurso(cadCurso).setVisible(true);
    }//GEN-LAST:event_jMenuItemCursoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTurmaActionPerformed
        new GuiTurma(cadTurma, cadCurso).setVisible(true);
    }//GEN-LAST:event_jMenuItemTurmaActionPerformed

    private void jMenuItemInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstrutorActionPerformed
        new GuiInstrutor(cadAlunoInstrutor).setVisible(true);
    }//GEN-LAST:event_jMenuItemInstrutorActionPerformed

    private void jMenuItemAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlunoActionPerformed
        new GuiAluno(cadAlunoInstrutor).setVisible(true);
    }//GEN-LAST:event_jMenuItemAlunoActionPerformed

    private void jMenuItemEfetuarMatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEfetuarMatriculaActionPerformed
        new GuiEfetuarMatricula(cadAlunoInstrutor, cadCurso, cadTurma, cadMatricula, cadAVista, cadAPrazo).setVisible(true);
    }//GEN-LAST:event_jMenuItemEfetuarMatriculaActionPerformed

    private void jMenuItemAlocarInstrutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlocarInstrutorActionPerformed
        new GuiAlocarInstrutor(cadCurso, cadTurma, cadAlunoInstrutor).setVisible(true);
    }//GEN-LAST:event_jMenuItemAlocarInstrutorActionPerformed

    private void jMenuItem2aAvaliacaoPOOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2aAvaliacaoPOOActionPerformed
        new GuiAvaliacao (cadAlunoInstrutor).setVisible(true);
    }//GEN-LAST:event_jMenuItem2aAvaliacaoPOOActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarTrabalhoPoo;
    private javax.swing.JMenu jMenuCadastros;
    private javax.swing.JMenuItem jMenuItem2aAvaliacaoPOO;
    private javax.swing.JMenuItem jMenuItemAlocarInstrutor;
    private javax.swing.JMenuItem jMenuItemAluno;
    private javax.swing.JMenuItem jMenuItemCurso;
    private javax.swing.JMenuItem jMenuItemEfetuarMatricula;
    private javax.swing.JMenuItem jMenuItemInstrutor;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTurma;
    private javax.swing.JMenu jMenuOperacoes;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparatorCadastros;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Curso> cadCurso = new ArrayList<Curso>();
    private ArrayList<Turma> cadTurma = new ArrayList<Turma>();
    private ArrayList<Matricula> cadMatricula = new ArrayList<Matricula>();
    private ArrayList<AVista> cadAVista = new ArrayList<AVista>();
    private ArrayList<APrazo> cadAPrazo = new ArrayList<APrazo>();
    private ArrayList<Pessoa> cadAlunoInstrutor  = new ArrayList<Pessoa>();
}
